# Generated by Django 4.2.2 on 2025-02-14 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonSocial', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nit', models.CharField(max_length=100, verbose_name='NIT')),
                ('logo', models.ImageField(blank=True, max_length=200, null=True, upload_to='negocio_logo/', verbose_name='Logo')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('sitioweb', models.URLField(blank=True, null=True, verbose_name='Sitio web')),
                ('telefono', models.CharField(blank=True, max_length=100, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Correo electrónico')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Negocio',
                'verbose_name_plural': 'Negocios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('numeroFactura', models.BigIntegerField(unique=True, verbose_name='Número de factura')),
                ('tipoDocumento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro civil')], default=False, max_length=20, verbose_name='Tipo de documento')),
                ('numeroDocumento', models.BigIntegerField(unique=True, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=30, unique=True, verbose_name='Correo electrónico')),
                ('nombreCliente', models.CharField(max_length=100, verbose_name='Cliente')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('pagado', models.BooleanField(default=False, verbose_name='Pagado')),
                ('fechaPago', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('productoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.productoservicio')),
                ('usuarioAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['numeroFactura'],
            },
        ),
    ]
