# Generated by Django 4.2.2 on 2025-02-15 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('factura', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='usuarioAdmin',
        ),
        migrations.AddField(
            model_name='negocio',
            name='propietario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
