# Generated by Django 4.2.2 on 2025-02-15 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_remove_factura_usuarioadmin_negocio_propietario'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoservicio',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factura.negocio'),
            preserve_default=False,
        ),
    ]
