# Generated by Django 4.2.2 on 2025-02-16 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_productoservicio_negocio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='fechaPago',
        ),
        migrations.AlterField(
            model_name='factura',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='factura.negocio'),
        ),
    ]
