# Generated by Django 4.2.2 on 2025-02-16 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0004_remove_factura_fechapago_alter_factura_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='productoServicio',
        ),
        migrations.AlterField(
            model_name='factura',
            name='email',
            field=models.EmailField(max_length=30, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numeroDocumento',
            field=models.BigIntegerField(verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro civil')], default='CC', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subtotal')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='factura.factura')),
                ('productoServicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factura.productoservicio')),
            ],
        ),
    ]
