# Generated by Django 4.2.2 on 2025-02-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_remove_factura_productoservicio_alter_factura_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='productoServicio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='factura.productoservicio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factura',
            name='email',
            field=models.EmailField(max_length=30, unique=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='numeroDocumento',
            field=models.BigIntegerField(unique=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='tipoDocumento',
            field=models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('PP', 'Pasaporte'), ('RC', 'Registro civil')], default=False, max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.DeleteModel(
            name='DetalleFactura',
        ),
    ]
