# Generated by Django 4.2.2 on 2025-02-18 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0007_remove_factura_productoservicio_alter_factura_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='factura.negocio'),
            preserve_default=False,
        ),
    ]
