# Generated by Django 4.2.2 on 2025-02-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0008_factura_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='qrCode',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='factura_qr/', verbose_name='QR Code'),
        ),
    ]
