# Generated by Django 4.2.2 on 2025-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0009_factura_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='qrCode',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code'),
        ),
    ]
